/**
* NSOA
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 1.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.swagger.client.models


/**
* 
* Values: alert,warning,content
*/
enum class ContentType(val value: kotlin.String){
    alert("alert"),
    warning("warning"),
    content("content");
}
