/**
* NSOA
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 1.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.swagger.client.models


/**
 * 
 * @param text 
 * @param image 
 * @param video 
 * @param article 
 */
data class ItemBody (
    val text: kotlin.String? = null,
    val image: kotlin.String? = null,
    val video: kotlin.String? = null,
    val article: kotlin.String? = null
) {
}